### ISSUE TITLE
Warn the users who are cloning the repo about it's size

### ISSUE THREAD

**Issue by FWJay** [bridgedotnet/Widgetoko#13]
I'm on a slow connection at a cafe, the download is stuck at 50% with almost 80MB downloaded and at 150kbps download speeds. will help if you warn people about the total size of the repo.

**Comment by geoffreymcgill** [comment]
It looks like the installers with committed to the repo at one point during their development. We'll look into some options. We really don't need the history commit history at this point, so maybe we can blow that away.

**Comment by geoffreymcgill** [comment]
Good news! We were able to clean up the history and remove that one giant commit that was messing with the repo size. Now the total history is < 1MB. 

Anyone that cloned the repo will need to do a fresh clone.

@FWJay thanks for pointing out the size issue. Should be good now.
